# Generated by Django 4.2 on 2023-04-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateTime', models.CharField(blank=True, max_length=255, null=True, verbose_name='日期')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='OriginPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='产地')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='OriginStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='产地')),
                ('count', models.CharField(blank=True, max_length=255, null=True, verbose_name='出现次数')),
            ],
        ),
        migrations.CreateModel(
            name='Prescript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True, verbose_name='药方id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='药方名')),
                ('recipe', models.CharField(blank=True, max_length=255, null=True, verbose_name='药方配方')),
                ('dosage', models.CharField(blank=True, max_length=255, null=True, verbose_name='使用方式')),
                ('excerpt', models.CharField(blank=True, max_length=255, null=True, verbose_name='出处')),
                ('indications', models.CharField(blank=True, max_length=255, null=True, verbose_name='功效')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='注意事项')),
                ('processing', models.CharField(blank=True, max_length=255, null=True, verbose_name='加工方式')),
                ('tcmName', models.CharField(blank=True, max_length=255, null=True, verbose_name='中药名称')),
                ('recipe_pz', models.CharField(blank=True, max_length=255, null=True, verbose_name='药方配料')),
            ],
        ),
    ]
