# Generated by Django 4.2 on 2023-04-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_historyprice_options_alter_info_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescript',
            name='recipe_pz',
            field=models.TextField(blank=True, null=True, verbose_name='药方配料'),
        ),
    ]
