# Generated by Django 4.2 on 2023-04-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_prescript_recipe_pz'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyprice',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='药材'),
        ),
        migrations.AddField(
            model_name='info',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='药材'),
        ),
        migrations.AddField(
            model_name='originprice',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='药材'),
        ),
        migrations.AddField(
            model_name='originstatistics',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='药材'),
        ),
    ]
